# colors

background            #111111
foreground            #D0D0D0

selection_background  #333333
selection_foreground  #FFFFFF

cursor                #CCCCCC
cursor_text_color     background

# black
color0   #1C1C1C
color8   #4C4C4C

# red
color1   #AF5F5F
color9   #FF6C6B

# green
color2   #87AF87
color10  #98BE65

# yellow
color3   #D7AF87
color11  #ECBE7B

# blue
color4   #5F87AF
color12  #51AFEF

# magenta
color5   #875F87
color13  #C678DD

# cyan
color6   #5FAFAF
color14  #46D9FF

# white
color7   #D0D0D0
color15  #FFFFFF
