# keymaps

map ctrl+shift+c       copy_to_clipboard
map ctrl+shift+v       paste_from_clipboard

# splits
map ctrl+s>pipe         launch --location=vsplit --cwd=current
map ctrl+s>minus        launch --location=hsplit --cwd=current

# window navigation (neovim style)
map ctrl+s>h           neighboring_window left
map ctrl+s>l           neighboring_window right
map ctrl+s>j           neighboring_window down
map ctrl+s>k           neighboring_window up

# window close
map ctrl+s>w           close_window

# tabs
map ctrl+s>c           new_tab
map ctrl+s>n           next_tab
map ctrl+s>p           previous_tab
map ctrl+s>r           set_tab_title
